"use client";

import { ChangeEvent, useMemo, useState } from "react";
import piexif from "piexifjs";
import { devicePresets } from "@/lib/device-presets";

type MetadataValue = string | number | boolean | null;
type MetadataMap = Record<string, MetadataValue>;
type IfdBlock = { [tag: number]: unknown };

type ExifDataShape = {
  "0th": IfdBlock;
  Exif: IfdBlock;
  GPS: IfdBlock;
  Interop: IfdBlock;
  "1st": IfdBlock;
  thumbnail: string | null;
};

type ReadResult = {
  previewUrl: string;
  fileName: string;
  fileType: string;
  metadata: MetadataMap;
  dataUrl: string;
  originalType: string;
  convertedToJpeg: boolean;
  fileSize: number;
  sourceFile: File;
  metadataNotice: string | null;
  aiDetected: boolean;
  editorDetected: boolean;
};

type MetadataSection = {
  title: string;
  entries: Array<[string, MetadataValue]>;
};

const AI_TOOL_PATTERNS = [
  "openai",
  "chatgpt",
  "dall-e",
  "gpt-image",
  "gptimage",
  "midjourney",
  "stable diffusion",
  "sdxl",
  "flux",
  "firefly",
  "adobe firefly",
  "leonardo",
  "ideogram",
  "canva ai",
  "canva",
  "bing image creator",
  "dreamstudio",
  "img2img",
  "text2img",
  "generated with ai",
  "ai generated",
  "ai-generated",
  "generated by ai",
  "created with ai",
  "generated by dalle",
  "midjourney.com",
  "stability ai",
  "stabilityai",
  "civitai",
  "comfyui",
  "automatic1111",
  "invokeai",
  "fooocus",
  "recraft",
];

const EDITOR_TOOL_PATTERNS = [
  "photoshop",
  "adobe",
  "lightroom",
  "camera raw",
  "gimp",
  "canva",
  "pixlr",
  "snapseed",
  "picsart",
  "photopea",
  "remini",
];

const formatDateTime = () => {
  const now = new Date();
  const pad = (value: number) => value.toString().padStart(2, "0");

  return `${now.getFullYear()}:${pad(now.getMonth() + 1)}:${pad(now.getDate())} ${pad(now.getHours())}:${pad(now.getMinutes())}:${pad(now.getSeconds())}`;
};

const sanitizeMetadataText = (value: unknown) => {
  if (typeof value !== "string") {
    return value;
  }

  const withoutControls = value.replace(/[\u0000-\u001F\u007F-\u009F\uFFFD]+/g, "").trim();
  const exifDateMatch = withoutControls.match(/\d{4}:\d{1,2}:\d{1,2}(?: \d{1,2}:\d{1,2}:\d{1,2})?/);

  if (exifDateMatch) {
    return exifDateMatch[0];
  }

  return withoutControls;
};

const normalizeExifDateValue = (value: unknown) => {
  const sanitized = sanitizeMetadataText(value);

  if (typeof sanitized !== "string") {
    return null;
  }

  const match = sanitized.match(
    /(\d{4}):(\d{1,2}):(\d{1,2})(?: (\d{1,2}):(\d{1,2}):(\d{1,2}))?/,
  );

  if (!match) {
    return sanitized || null;
  }

  const [, year, month, day, hour = "0", minute = "0", second = "0"] = match;
  const pad = (input: string) => input.padStart(2, "0");

  return `${year}:${pad(month)}:${pad(day)} ${pad(hour)}:${pad(minute)}:${pad(second)}`;
};

const isDateLikeMetadataKey = (key: string) => /date|time/i.test(key);

const isPlausibleMetadataDate = (date: Date) => {
  const year = date.getFullYear();

  return Number.isFinite(date.getTime()) && year >= 1990 && year <= 2100;
};

const formatDisplayDate = (date: Date) =>
  date.toLocaleString("en-GB", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  });

const normalizeGenericDateString = (value: string) => {
  const parsed = new Date(value);

  if (Number.isNaN(parsed.getTime()) || !isPlausibleMetadataDate(parsed)) {
    return null;
  }

  return formatDisplayDate(parsed);
};

const randomDigits = (length: number) => {
  let result = "";

  for (let index = 0; index < length; index += 1) {
    result += Math.floor(Math.random() * 10).toString();
  }

  return result;
};

const inferMimeType = (file: File) => {
  if (file.type) {
    return file.type;
  }

  const lowerName = file.name.toLowerCase();

  if (lowerName.endsWith(".png")) {
    return "image/png";
  }

  if (lowerName.endsWith(".jpg") || lowerName.endsWith(".jpeg")) {
    return "image/jpeg";
  }

  if (lowerName.endsWith(".webp")) {
    return "image/webp";
  }

  return "application/octet-stream";
};

const buildDeviceFileName = (preset: (typeof devicePresets)[number]) => {
  const now = new Date();
  const pad = (value: number) => value.toString().padStart(2, "0");
  const year = now.getFullYear();
  const month = pad(now.getMonth() + 1);
  const day = pad(now.getDate());
  const hours = pad(now.getHours());
  const minutes = pad(now.getMinutes());
  const seconds = pad(now.getSeconds());

  if (preset.filenameStyle === "samsung") {
    return `${year}${month}${day}_${hours}${minutes}${seconds}.jpg`;
  }

  if (preset.filenameStyle === "iphone") {
    return `IMG_${randomDigits(4)}.JPG`;
  }

  if (preset.filenameStyle === "canon") {
    return `_MG_${randomDigits(4)}.JPG`;
  }

  return `IMG_${randomDigits(4)}.JPG`;
};

const formatMetadata = (raw: Record<string, unknown> | null | undefined): MetadataMap => {
  if (!raw) {
    return {};
  }

  return Object.entries(raw).reduce<MetadataMap>((acc, [key, value]) => {
    // ExposureTime কে fraction হিসেবে দেখাও
    if (key === "ExposureTime" && typeof value === "number" && value < 1) {
      const denominator = Math.round(1 / value);
      acc[key] = `1/${denominator}`;
      return acc;
    }

    if (value instanceof Date) {
      if (!isDateLikeMetadataKey(key) || isPlausibleMetadataDate(value)) {
        acc[key] = formatDisplayDate(value);
      }
      return acc;
    }

    if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
      if (typeof value === "string" && isDateLikeMetadataKey(key)) {
        const exifDate = normalizeExifDateValue(value);

        if (exifDate) {
          acc[key] = exifDate;
          return acc;
        }

        const genericDate = normalizeGenericDateString(value);

        if (genericDate) {
          acc[key] = genericDate;
          return acc;
        }

        return acc;
      }

      acc[key] = sanitizeMetadataText(value) as MetadataValue;
      return acc;
    }

    if (Array.isArray(value)) {
      acc[key] = value.join(", ");
      return acc;
    }

    if (value && typeof value === "object") {
      acc[key] = JSON.stringify(value);
    }

    return acc;
  }, {});
};

const toBlob = async (dataUrl: string) => {
  const response = await fetch(dataUrl);
  return response.blob();
};

const binaryStringToDataUrl = (bytes: Uint8Array, mimeType: string) =>
  new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = () => reject(new Error("Could not rebuild the image."));
    const safeBytes = new Uint8Array(bytes);
    reader.readAsDataURL(new Blob([safeBytes.buffer], { type: mimeType }));
  });

const fileToDataUrl = (file: File) =>
  new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = () => reject(new Error("Could not read the image."));
    reader.readAsDataURL(file);
  });

const fileToArrayBuffer = (file: File) =>
  new Promise<ArrayBuffer>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as ArrayBuffer);
    reader.onerror = () => reject(new Error("Could not read the image binary data."));
    reader.readAsArrayBuffer(file);
  });

const cleanImageWithServer = async (file: File,iccProfile: "srgb" | "p3" = "srgb") => {
  const formData = new FormData();
  formData.append("file", file);
formData.append("iccProfile", iccProfile); 
  const response = await fetch("/api/clean-image", {
    method: "POST",
    body: formData,
  });

  if (!response.ok) {
    throw new Error("Server-side image cleaning failed.");
  }

  const cleanedBlob = await response.blob();
  const normalizedName = file.name.replace(/\.[^.]+$/, "") || "image";
  const normalizedFile = new File([cleanedBlob], `${normalizedName}.jpg`, {
    type: "image/jpeg",
  });

  return {
    normalizedFile,
    dataUrl: await fileToDataUrl(normalizedFile),
    originalType: file.type || "application/octet-stream",
    convertedToJpeg: true,
  };
};

const loadImageElement = (dataUrl: string) =>
  new Promise<HTMLImageElement>((resolve, reject) => {
    const image = new Image();
    image.onload = () => resolve(image);
    image.onerror = () => reject(new Error("Could not render the image."));
    image.src = dataUrl;
  });

const removeIccFromDataUrl = async (dataUrl: string): Promise<string> => {
  const sourceBlob = await toBlob(dataUrl);
  const sourceBytes = new Uint8Array(await sourceBlob.arrayBuffer());

  if (sourceBytes.length < 4 || sourceBytes[0] !== 0xff || sourceBytes[1] !== 0xd8) {
    return dataUrl;
  }

  const chunks: Uint8Array[] = [sourceBytes.subarray(0, 2)];
  let offset = 2;

  while (offset < sourceBytes.length) {
    if (sourceBytes[offset] !== 0xff) {
      break;
    }

    const marker = sourceBytes[offset + 1];

    if (marker === 0xda) {
      chunks.push(sourceBytes.subarray(offset));
      break;
    }

    if (offset + 3 >= sourceBytes.length) {
      break;
    }

    const segmentLength = (sourceBytes[offset + 2] << 8) | sourceBytes[offset + 3];
    const segmentEnd = offset + 2 + segmentLength;

    if (segmentEnd > sourceBytes.length) {
      break;
    }

    if (marker === 0xe2) {
      const tagBytes = sourceBytes.subarray(offset + 4, offset + 16);
      const tag = new TextDecoder("ascii").decode(tagBytes);

      if (tag.startsWith("ICC_PROFILE")) {
        offset = segmentEnd;
        continue;
      }
    }

    chunks.push(sourceBytes.subarray(offset, segmentEnd));
    offset = segmentEnd;
  }

  const totalLength = chunks.reduce((sum, chunk) => sum + chunk.length, 0);
  const merged = new Uint8Array(totalLength);
  let writeOffset = 0;

  chunks.forEach((chunk) => {
    merged.set(chunk, writeOffset);
    writeOffset += chunk.length;
  });

  return binaryStringToDataUrl(merged, "image/jpeg");
};

const safeExifLoad = (dataUrl: string): ExifDataShape => {
  try {
    return piexif.load(dataUrl);
  } catch {
    return {
      "0th": {},
      Exif: {},
      GPS: {},
      Interop: {},
      "1st": {},
      thumbnail: null,
    };
  }
};

const extractPiexifMetadata = (dataUrl: string): MetadataMap => {
  try {
    const exifData = piexif.load(dataUrl);

    return {
      Make:
        typeof exifData["0th"][piexif.ImageIFD.Make] === "string"
          ? String(sanitizeMetadataText(exifData["0th"][piexif.ImageIFD.Make]))
          : null,
      Model:
        typeof exifData["0th"][piexif.ImageIFD.Model] === "string"
          ? String(sanitizeMetadataText(exifData["0th"][piexif.ImageIFD.Model]))
          : null,
      Software:
        typeof exifData["0th"][piexif.ImageIFD.Software] === "string"
          ? String(sanitizeMetadataText(exifData["0th"][piexif.ImageIFD.Software]))
          : null,
      DateTime:
        typeof exifData["0th"][piexif.ImageIFD.DateTime] === "string"
          ? normalizeExifDateValue(exifData["0th"][piexif.ImageIFD.DateTime])
          : null,
      DateTimeOriginal:
        typeof exifData.Exif[piexif.ExifIFD.DateTimeOriginal] === "string"
          ? normalizeExifDateValue(exifData.Exif[piexif.ExifIFD.DateTimeOriginal])
          : null,
      DateTimeDigitized:
        typeof exifData.Exif[piexif.ExifIFD.DateTimeDigitized] === "string"
          ? normalizeExifDateValue(exifData.Exif[piexif.ExifIFD.DateTimeDigitized])
          : null,
      LensModel:
        typeof exifData.Exif[piexif.ExifIFD.LensModel] === "string"
          ? String(sanitizeMetadataText(exifData.Exif[piexif.ExifIFD.LensModel]))
          : null,
    };
  } catch {
    return {};
  }
};

const detectAiMetadata = (metadata: MetadataMap): MetadataMap => {
  const matchedSignals = Object.entries(metadata)
    .filter(([, value]) => value !== null)
    .filter(([, value]) => AI_TOOL_PATTERNS.some((pattern) => String(value).toLowerCase().includes(pattern)));

  if (!matchedSignals.length) {
    return {};
  }

  return {
    AIContentDetected: "Yes",
    AIDetectionSource: matchedSignals.map(([key]) => key).join(", "),
    AIDetectionMatch: matchedSignals.map(([, value]) => String(value)).join(" | ").slice(0, 300),
  };
};

const detectAiBinaryTrace = async (file: File): Promise<MetadataMap> => {
  try {
    const buffer = await fileToArrayBuffer(file);
    const latin1 = new TextDecoder("latin1").decode(new Uint8Array(buffer)).toLowerCase();
    const matches = AI_TOOL_PATTERNS.filter((pattern) => latin1.includes(pattern));

    if (!matches.length) {
      return {};
    }

    return {
      AIContentDetected: "Yes",
      AIDetectionSource: "Binary/XMP scan",
      AIDetectionMatch: matches.slice(0, 6).join(", "),
    };
  } catch {
    return {};
  }
};

const detectEditorMetadata = (metadata: MetadataMap): MetadataMap => {
  const matchedSignals = Object.entries(metadata)
    .filter(([, value]) => value !== null)
    .filter(([, value]) => EDITOR_TOOL_PATTERNS.some((pattern) => String(value).toLowerCase().includes(pattern)));

  const photoshopBlockDetected =
    String(metadata.PhotoshopResourceDetected ?? "").toLowerCase() === "yes" ||
    String(metadata.XmpPacketDetected ?? "").toLowerCase() === "yes" ||
    String(metadata.IptcBlockDetected ?? "").toLowerCase() === "yes";

  if (!matchedSignals.length && !photoshopBlockDetected) {
    return {};
  }

  return {
    EditedImageDetected: "Yes",
    EditDetectionSource: matchedSignals.length
      ? matchedSignals.map(([key]) => key).join(", ")
      : "Photoshop/XMP resource blocks",
    EditDetectionMatch: matchedSignals.length
      ? matchedSignals.map(([, value]) => String(value)).join(" | ").slice(0, 300)
      : "Photoshop/XMP resource blocks detected",
  };
};

const extractFirstMatch = (input: string, pattern: RegExp) => {
  const match = input.match(pattern);
  return match?.[1]?.trim() || null;
};

const decodeXmlValue = (value: string | null) => {
  if (!value) {
    return null;
  }

  return value
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">");
};

const extractContainerMetadata = async (file: File): Promise<MetadataMap> => {
  try {
    const buffer = await fileToArrayBuffer(file);
    const bytes = new Uint8Array(buffer);
    const latin1 = new TextDecoder("latin1").decode(bytes);
    const upperType = inferMimeType(file).toUpperCase();

    const hasIccProfile =
      latin1.includes("ICC_PROFILE") ||
      latin1.includes("iCCP") ||
      latin1.includes("ICCP");
    const hasXmpPacket =
      latin1.includes("http://ns.adobe.com/xap/1.0/") ||
      latin1.includes("<x:xmpmeta") ||
      latin1.includes("XML:com.adobe.xmp");
    const hasPhotoshopResource = latin1.includes("Photoshop 3.0");
    const hasIptcBlock =
      latin1.includes("8BIM") ||
      latin1.includes("IPTC") ||
      latin1.includes("http://ns.adobe.com/photoshop/1.0/");
    const hasExifSegment = latin1.includes("Exif");
    const hasGpsHints =
      latin1.includes("GPSLatitude") ||
      latin1.includes("GPSLongitude") ||
      latin1.includes("gps");
    const creatorTool = decodeXmlValue(
      extractFirstMatch(latin1, /(?:xmp:)?CreatorTool="([^"]+)"/i) ||
        extractFirstMatch(latin1, /<xmp:CreatorTool>([^<]+)<\/xmp:CreatorTool>/i),
    );
    const metadataDate = decodeXmlValue(
      extractFirstMatch(latin1, /<(?:xmp:)?MetadataDate>([^<]+)<\/(?:xmp:)?MetadataDate>/i),
    );
    const modifyDate = decodeXmlValue(
      extractFirstMatch(latin1, /<(?:xmp:)?ModifyDate>([^<]+)<\/(?:xmp:)?ModifyDate>/i),
    );
    const photoshopDateCreated = decodeXmlValue(
      extractFirstMatch(latin1, /<photoshop:DateCreated>([^<]+)<\/photoshop:DateCreated>/i),
    );
    const documentId = decodeXmlValue(
      extractFirstMatch(latin1, /<xmpMM:DocumentID>([^<]+)<\/xmpMM:DocumentID>/i),
    );
    const instanceId = decodeXmlValue(
      extractFirstMatch(latin1, /<xmpMM:InstanceID>([^<]+)<\/xmpMM:InstanceID>/i),
    );
    const historySoftwareAgent = decodeXmlValue(
      extractFirstMatch(latin1, /<stEvt:softwareAgent>([^<]+)<\/stEvt:softwareAgent>/i),
    );
    const derivedFromSoftware = decodeXmlValue(
      extractFirstMatch(latin1, /<stRef:softwareAgent>([^<]+)<\/stRef:softwareAgent>/i),
    );
    const adobeSoftwareTrace =
      creatorTool ||
      historySoftwareAgent ||
      derivedFromSoftware ||
      (latin1.match(/Adobe (?:Photoshop|Lightroom|Illustrator|Camera Raw)[^<\0\r\n]*/i)?.[0] ?? null);
    const editingTraceSummary = [
      creatorTool,
      historySoftwareAgent,
      derivedFromSoftware,
      hasPhotoshopResource ? "Photoshop resource block" : null,
      hasXmpPacket ? "XMP packet" : null,
      hasIptcBlock ? "IPTC/8BIM block" : null,
    ]
      .filter((value, index, list): value is string => Boolean(value) && list.indexOf(value) === index)
      .join(" | ");

    return stripEmptyMetadata({
      ContainerType: upperType,
      ExifSegmentDetected: hasExifSegment ? "Yes" : "No",
      XmpPacketDetected: hasXmpPacket ? "Yes" : "No",
      IccProfileDetected: hasIccProfile ? "Yes" : "No",
      PhotoshopResourceDetected: hasPhotoshopResource ? "Yes" : "No",
      IptcBlockDetected: hasIptcBlock ? "Yes" : "No",
      GpsHintDetected: hasGpsHints ? "Yes" : "No",
      CreatorTool: creatorTool,
      AdobeSoftwareTrace: adobeSoftwareTrace,
      EditingTraceSummary: editingTraceSummary || null,
      MetadataDate: metadataDate,
      ModifyDate: modifyDate,
      PhotoshopDateCreated: photoshopDateCreated,
      XmpDocumentId: documentId,
      XmpInstanceId: instanceId,
      HistorySoftwareAgent: historySoftwareAgent,
      DerivedFromSoftwareAgent: derivedFromSoftware,
    });
  } catch {
    return {};
  }
};

const readExifMetadata = async (file: File): Promise<{ metadata: MetadataMap; notice: string | null }> => {
  try {
    const exifr = await import("exifr/dist/full.esm.mjs");
    const parsed = await exifr.parse(file, {
      tiff: true,
      xmp: true,
      icc: false,
      iptc: true,
      jfif: false,
      ihdr: true,
      exif: true,
      gps: true,
      interop: true,
    });

    return {
      metadata: formatMetadata(parsed),
      notice: null,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message.toLowerCase() : "";

    if (message.includes("unknown file format")) {
      return {
        metadata: {},
        notice:
          "This image format could be loaded, but its embedded metadata could not be parsed fully. You can still sanitize and inject new metadata.",
      };
    }

    return {
      metadata: {},
      notice: "Embedded metadata could not be read from this file, but you can still continue.",
    };
  }
};

const stripEmptyMetadata = (metadata: MetadataMap) =>
  Object.fromEntries(
    Object.entries(metadata).filter(([key, value]) => {
      const normalizedKey = key.trim().toLowerCase();

      if (
        normalizedKey === "profile_copyright" ||
        normalizedKey === "profilecopyright" ||
        normalizedKey === "profile copyright"
      ) {
        return false;
      }

      return value !== null && value !== "" && value !== "undefined";
    }),
  );

const formatBytes = (bytes: number) => {
  if (bytes < 1024) {
    return `${bytes} B`;
  }

  if (bytes < 1024 * 1024) {
    return `${(bytes / 1024).toFixed(1)} KB`;
  }

  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
};

const groupMetadata = (metadata: MetadataMap, query: string): MetadataSection[] => {
  const normalizedQuery = query.trim().toLowerCase();
  const filteredEntries = Object.entries(metadata).filter(([key, value]) => {
    if (!normalizedQuery) {
      return true;
    }

    return `${key} ${String(value)}`.toLowerCase().includes(normalizedQuery);
  });

  const sections: Record<string, Array<[string, MetadataValue]>> = {
    Identity: [],
    DateTime: [],
    Camera: [],
    File: [],
    GPS: [],
    Other: [],
  };

  filteredEntries.forEach(([key, value]) => {
    const lowerKey = key.toLowerCase();

    if (["make", "model", "software", "artist", "ownername", "creatortool", "adobesoftwaretrace", "historysoftwareagent", "derivedfromsoftwareagent", "editingtracesummary", "injectedbrand", "injecteddevice", "injectedpresetid"].some((token) => lowerKey.includes(token))) {
      sections.Identity.push([key, value]);
      return;
    }

    if (lowerKey.includes("date") || lowerKey.includes("time")) {
      sections.DateTime.push([key, value]);
      return;
    }

    if (
      ["lens", "iso", "fnumber", "exposure", "focal", "whitebalance", "flash", "orientation", "metering", "scene"].some((token) =>
        lowerKey.includes(token),
      )
    ) {
      sections.Camera.push([key, value]);
      return;
    }

    if (["width", "height", "dimension", "colorspace", "format", "mime", "file", "outputfilename", "autoconvertedtojpeg", "originalfiletype"].some((token) =>
      lowerKey.includes(token),
    )) {
      sections.File.push([key, value]);
      return;
    }

    if (lowerKey.includes("gps") || lowerKey.includes("latitude") || lowerKey.includes("longitude")) {
      sections.GPS.push([key, value]);
      return;
    }

    sections.Other.push([key, value]);
  });

  return Object.entries(sections)
    .map(([title, entries]) => ({ title, entries }))
    .filter((section) => section.entries.length > 0);
};

const randomInRange = (min: number, max: number) =>
  Math.floor(Math.random() * (max - min + 1)) + min;

const buildSanitizedExif = (
  preset: (typeof devicePresets)[number],
  currentDateTime: string,
  dimensions?: { width: number; height: number }
): ExifDataShape => {
  // dynamic exposure simulation
  const iso = randomInRange(...preset.isoRange);
  const exposureDenominator = randomInRange(...preset.shutterRange);

  
     
const subSec = String(randomInRange(100, 999));
const subSec2 = String(randomInRange(100, 999));
const subSec3 = String(randomInRange(100, 999));


  const exif: ExifDataShape = {
    "0th": {
      [piexif.ImageIFD.Make]: preset.make,
      [piexif.ImageIFD.Model]: preset.model,
      [piexif.ImageIFD.Software]: preset.software,
      [piexif.ImageIFD.DateTime]: currentDateTime,

      // realism
      [piexif.ImageIFD.Orientation]: 1,
      [piexif.ImageIFD.XResolution]: [72, 1],
      [piexif.ImageIFD.YResolution]: [72, 1],
      [piexif.ImageIFD.ResolutionUnit]: 2,
      [piexif.ImageIFD.YCbCrPositioning]: 1,

      ...(preset.artist
        ? { [piexif.ImageIFD.Artist]: preset.artist }
        : {}),
    },

    Exif: {
      // timestamps
      [piexif.ExifIFD.DateTimeOriginal]: currentDateTime,
      [piexif.ExifIFD.DateTimeDigitized]: currentDateTime,

      // subsec (device behavior)
      ...(preset.hasSubSecTime && {
     [piexif.ExifIFD.SubSecTime]: subSec,
[piexif.ExifIFD.SubSecTimeOriginal]: subSec2,
[piexif.ExifIFD.SubSecTimeDigitized]: subSec3,
      }),

      // exposure physics
      [piexif.ExifIFD.FNumber]: [Math.round(preset.fNumber * 100), 100],
      [piexif.ExifIFD.FocalLength]: [Math.round(preset.focalLength * 100), 100],
      [piexif.ExifIFD.ISOSpeedRatings]: iso,
      [piexif.ExifIFD.ExposureTime]: [1, exposureDenominator],

      [piexif.ExifIFD.ExposureProgram]:
        preset.exposureProgram === "Manual" ? 1 : 2,

         [piexif.ExifIFD.SceneCaptureType]: randomInRange(0, 2),
  [piexif.ExifIFD.SensingMethod]: 2,
  [piexif.ExifIFD.ExposureMode]: 0,
  [piexif.ExifIFD.CustomRendered]: 0,
  [piexif.ExifIFD.ExposureBiasValue]:  [0, 1],
[piexif.ExifIFD.MaxApertureValue]: [Math.round(preset.fNumber * 100), 100],

      [piexif.ExifIFD.MeteringMode]: 5,
      [piexif.ExifIFD.LightSource]: 0,
      [piexif.ExifIFD.Flash]: 0,
      [piexif.ExifIFD.WhiteBalance]: 0,
[piexif.ExifIFD.SceneType]: "\x01",   
[piexif.ExifIFD.FileSource]: "\x03",
      // lens
      [piexif.ExifIFD.LensModel]: preset.lensModel,
      ...(preset.lensMake && {
        [piexif.ExifIFD.LensMake]: preset.lensMake,
      }),
 


      // image info
      [piexif.ExifIFD.ColorSpace]: preset.colorSpace,
      [piexif.ExifIFD.PixelXDimension]: dimensions?.width ?? preset.resolution[0],
      [piexif.ExifIFD.PixelYDimension]: dimensions?.height ?? preset.resolution[1],

      // subtle realism (not too perfect)
     [piexif.ExifIFD.BodySerialNumber]: randomDigits(10),
    },

    GPS: {},

    Interop: {},

    "1st": {},

    // optional future upgrade: thumbnail
    thumbnail: null,
  };

  return exif;
};
export default function Home() {
  const [selectedPresetId, setSelectedPresetId] = useState(devicePresets[0]?.id ?? "");
  const [readResult, setReadResult] = useState<ReadResult | null>(null);
  const [updatedMetadata, setUpdatedMetadata] = useState<MetadataMap | null>(null);
  const [downloadUrl, setDownloadUrl] = useState<string | null>(null);
  const [status, setStatus] = useState("Upload an image, review its metadata, sanitize it, then inject a device preset.");
  const [busy, setBusy] = useState(false);
  const [sanitizeEnabled, setSanitizeEnabled] = useState(true);
  const [inspectorQuery, setInspectorQuery] = useState("");
  const [showRawMetadata, setShowRawMetadata] = useState(false);
  const [isCurrentMetadataExpanded, setIsCurrentMetadataExpanded] = useState(false);
  const [showDownloadPopup, setShowDownloadPopup] = useState(false);

  const selectedPreset = useMemo(
    () => devicePresets.find((preset) => preset.id === selectedPresetId) ?? devicePresets[0],
    [selectedPresetId],
  );

  const handleFileChange = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];

    if (!file) {
      return;
    }

    setBusy(true);
    setUpdatedMetadata(null);
    setDownloadUrl(null);
    setShowDownloadPopup(false);

    try {
      const originalDataUrl = await fileToDataUrl(file);
      const { metadata: parsedMetadata, notice: metadataNotice } = await readExifMetadata(file);
      const containerMetadata = await extractContainerMetadata(file);
      const aiBinaryMetadata = await detectAiBinaryTrace(file);
      const piexifMetadata =
        file.type.includes("jpeg") || file.name.match(/\.(jpe?g)$/i)
          ? extractPiexifMetadata(originalDataUrl)
          : {};
      const mergedMetadata = stripEmptyMetadata({
        ...containerMetadata,
        ...piexifMetadata,
        ...parsedMetadata,
      });
      const currentMetadata = stripEmptyMetadata({
        ...mergedMetadata,
        ...detectAiMetadata(mergedMetadata),
        ...aiBinaryMetadata,
        ...detectEditorMetadata(mergedMetadata),
      });

      setReadResult({
        previewUrl: URL.createObjectURL(file),
        fileName: file.name,
        fileType: inferMimeType(file),
        metadata: currentMetadata,
        dataUrl: originalDataUrl,
        originalType: inferMimeType(file),
        convertedToJpeg: false,
        fileSize: file.size,
        sourceFile: file,
        metadataNotice,
        aiDetected: "AIContentDetected" in currentMetadata,
        editorDetected: "EditedImageDetected" in currentMetadata,
      });
      setIsCurrentMetadataExpanded(false);

      setStatus(
        Object.keys(currentMetadata).length
          ? metadataNotice ??
            "The original file metadata has been read. Existing metadata will be replaced during injection."
          : "The image was loaded, but no readable metadata was found. Photos downloaded from Google, Facebook, Messenger, or other social platforms often have EXIF removed. A clean output will be generated during injection.",
      );
    } catch (error) {
      setReadResult(null);
      setStatus(error instanceof Error ? error.message : "There was a problem reading the metadata.");
    } finally {
      setBusy(false);
    }
  };

const handleInject = async () => {
    if (!readResult || !selectedPreset) {
      return;
    }

    setBusy(true);

    try {
      const normalized = await cleanImageWithServer(
  readResult.sourceFile,
  selectedPreset.iccProfile // এটা pass করুন
);

      // FORCE REMOVE ALL OLD METADATA
      const cleanCanvas = document.createElement("canvas");
      const img = await loadImageElement(normalized.dataUrl);

      cleanCanvas.width = img.naturalWidth;
      cleanCanvas.height = img.naturalHeight;

      const ctx = cleanCanvas.getContext("2d");
      ctx?.drawImage(img, 0, 0);

      // FIX #4 & #6: quality 0.92 — Samsung real quality এর কাছাকাছি
     

      const fullyCleanDataUrl = await removeIccFromDataUrl(
        cleanCanvas.toDataURL("image/jpeg", 0.92)
      );



      const cleanedImage = await loadImageElement(fullyCleanDataUrl);

      const currentDateTime = formatDateTime();

      const exifData = sanitizeEnabled
        ? buildSanitizedExif(selectedPreset, currentDateTime, {
              width: cleanedImage.naturalWidth,
  height: cleanedImage.naturalHeight,
          })
        : safeExifLoad(normalized.dataUrl);

      // FIX #1: MakerNote সম্পূর্ণ বাদ — random bytes দেওয়ার চেয়ে না থাকা ভালো
      delete exifData.Exif[piexif.ExifIFD.MakerNote];

      // FIX #2: GPS — Samsung/iPhone-এ GPSVersionID সবসময় থাকে
      if (selectedPreset.hasGpsVersionId) {
        exifData.GPS = {
          
        };
      } else {
        // Canon DSLR-এ GPS নেই — empty রাখা স্বাভাবিক
        exifData.GPS = {};
      }

      exifData.Interop = {};

      // FIX #3: Thumbnail generate করো — real camera সবসময় দেয়
      const thumbCanvas = document.createElement("canvas");
      const THUMB_W = 160;
      const THUMB_H = Math.round((cleanedImage.naturalHeight / cleanedImage.naturalWidth) * THUMB_W);
      thumbCanvas.width = THUMB_W;
      thumbCanvas.height = THUMB_H;
      const thumbCtx = thumbCanvas.getContext("2d");
      thumbCtx?.drawImage(cleanedImage, 0, 0, THUMB_W, THUMB_H);
      const thumbDataUrl = thumbCanvas.toDataURL("image/jpeg", 0.6);
      const thumbBase64 = thumbDataUrl.split(",")[1];
      const thumbBinary = atob(thumbBase64);

 exifData["1st"] = {
  [piexif.ImageIFD.JPEGInterchangeFormat]: 0,
  [piexif.ImageIFD.JPEGInterchangeFormatLength]: thumbBinary.length,
  [piexif.ImageIFD.Compression]: 6,
  [piexif.ImageIFD.XResolution]: [72, 1],
  [piexif.ImageIFD.YResolution]: [72, 1],
  [piexif.ImageIFD.ResolutionUnit]: 2,
  [piexif.ImageIFD.Orientation]: 1,
  256: THUMB_W,   // ImageWidth tag number directly
  257: THUMB_H,   // ImageLength tag number directly
};
      exifData.thumbnail = thumbBinary;

      // preset values override (ensure correct)
      exifData["0th"][piexif.ImageIFD.Make] = selectedPreset.make;
      exifData["0th"][piexif.ImageIFD.Model] = selectedPreset.model;
      exifData["0th"][piexif.ImageIFD.Software] = selectedPreset.software;
      exifData["0th"][piexif.ImageIFD.DateTime] = currentDateTime;
      exifData.Exif[piexif.ExifIFD.DateTimeOriginal] = currentDateTime;
      exifData.Exif[piexif.ExifIFD.DateTimeDigitized] = currentDateTime;
      exifData.Exif[piexif.ExifIFD.LensModel] = selectedPreset.lensModel;

      // step 1: empty EXIF দিয়ে পুরানো সব metadata wipe
      const emptyExif = piexif.dump({
        "0th": {},
        Exif: {},
        GPS: {},
        Interop: {},
        "1st": {},
        thumbnail: null,
      });

      const cleanedBase = piexif.insert(emptyExif, fullyCleanDataUrl);

      // step 2: real EXIF inject
      const exifBytes = piexif.dump(exifData);
      const updatedDataUrl = piexif.insert(exifBytes, cleanedBase);

      const updatedBlob = await toBlob(updatedDataUrl);
      const deviceFileName = buildDeviceFileName(selectedPreset);
      const updatedFile = new File([updatedBlob], deviceFileName, {
        type: "image/jpeg",
      });

      const { metadata: reparsedMetadata } = await readExifMetadata(updatedFile);

      const parsedMetadata = stripEmptyMetadata({
        ...reparsedMetadata,
      });

      setUpdatedMetadata({
        ...parsedMetadata,
        
        
        
      });

      setDownloadUrl(URL.createObjectURL(updatedBlob));
      setStatus(
        `${selectedPreset.name} preset has been injected${sanitizeEnabled ? " and previous editor/device traces were sanitized" : ""}. You can now download the updated image.`,
      );
    } catch (error) {
      setStatus(error instanceof Error ? error.message : "There was a problem injecting metadata.");
    } finally {
      setBusy(false);
    }
  };

  const renderMetadataItems = (metadata: MetadataMap, mode: "current" | "injected") => {
    const entries = Object.entries(metadata);
    const groupedSections = groupMetadata(metadata, inspectorQuery);

    if (!entries.length) {
      return <p className="text-sm text-[var(--muted)]">No readable EXIF metadata was found in this image.</p>;
    }

    if (showRawMetadata) {
      return (
        <pre className="overflow-x-auto rounded-[1.5rem] border border-[var(--line)] bg-[#fffaf2] p-4 text-xs leading-6 text-[var(--foreground)]">
          {JSON.stringify(metadata, null, 2)}
        </pre>
      );
    }

    if (!groupedSections.length) {
      return (
        <div className="rounded-[1.5rem] border border-dashed border-[var(--line)] bg-white/55 px-5 py-8 text-sm leading-7 text-[var(--muted)]">
          No matching metadata was found for `{inspectorQuery}`.
        </div>
      );
    }

    return (
      <div className="grid gap-4">
        {groupedSections.map((section) => (
          <div key={`${mode}-${section.title}`} className="rounded-[1.5rem] border border-[var(--line)] bg-white/60 p-4">
            <div className="mb-3 flex flex-col items-start gap-2 sm:flex-row sm:items-center sm:justify-between">
              <p className="text-xs font-semibold uppercase tracking-[0.22em] text-[var(--accent-deep)]">
                {section.title}
              </p>
              <span className="rounded-full bg-[#fff3e8] px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-[var(--muted)]">
                {section.entries.length} fields
              </span>
            </div>

            <div className="grid gap-3">
              {section.entries.map(([key, value]) => (
                <div key={key} className="rounded-2xl border border-[var(--line)] bg-white/70 px-4 py-3">
                  <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--muted)]">{key}</p>
                  <p className="mt-1 break-words text-sm text-[var(--foreground)]">{String(value)}</p>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>
    );
  };

  return (
    <main className="mx-auto flex min-h-screen w-full max-w-7xl flex-col px-3 py-5 sm:px-6 sm:py-8 lg:px-8">
      <section className="glass-panel-strong relative overflow-hidden rounded-[1.5rem] px-4 py-6 sm:rounded-[2rem] sm:px-8 sm:py-8 lg:px-10">
        <div className="absolute inset-x-0 top-0 h-24 bg-gradient-to-r from-[rgba(199,100,42,0.18)] via-transparent to-[rgba(20,112,119,0.15)]" />
        <div className="relative flex flex-col gap-8">
          <div className="mx-auto flex max-w-5xl flex-col items-center text-center">
            <h1 className="font-heading text-lg font-semibold leading-tight tracking-tight text-[var(--foreground)] sm:text-2xl lg:text-3xl">
              Review, clean, and inject device metadata.
            </h1>
            <div className="mt-5 max-w-3xl rounded-[1.5rem] border border-[var(--line)] bg-white/60 px-5 py-4 shadow-[0_16px_36px_rgba(84,60,32,0.08)] backdrop-blur">
              <p className="text-sm leading-7 text-[var(--muted)] sm:text-base sm:leading-8">
                Inspect EXIF and embedded image details, clean editor traces, and apply a fresh device identity with a more polished metadata workflow for Samsung, iPhone, Canon, and more.
              </p>
            </div>
          </div>

          <div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
            <div className="glass-panel rounded-[1.75rem] p-5 sm:p-6">
              <p className="text-sm font-semibold uppercase tracking-[0.2em] text-[var(--accent-deep)]">
                1. Upload Image
              </p>
              <label className="mt-4 flex cursor-pointer flex-col items-center justify-center rounded-[1.5rem] border border-dashed border-[var(--line)] bg-white/65 px-6 py-10 text-center transition hover:bg-white">
                <span className="text-lg font-semibold text-[var(--foreground)]">
                  Choose an image here
                </span>
                <span className="mt-2 text-sm text-[var(--muted)]">
                  JPG, JPEG, PNG, and WEBP are supported
                </span>
                <input
                  type="file"
                  accept="image/jpeg,image/jpg,image/png,image/webp"
                  className="hidden"
                  onChange={handleFileChange}
                />
              </label>

              <div className="mt-5 rounded-[1.5rem] border border-[var(--line)] bg-[#fffaf2] px-4 py-4">
                <p className="text-sm font-semibold text-[var(--foreground)]">Status</p>
                <p className="mt-2 text-sm leading-7 text-[var(--muted)]">{busy ? "Working..." : status}</p>
              </div>

              {readResult ? (
                <div className="mt-5 grid gap-4 sm:grid-cols-[1fr_auto] sm:items-center">
                  <div>
                    <p className="text-sm font-semibold text-[var(--foreground)]">{readResult.fileName}</p>
                    <p className="mt-1 text-sm text-[var(--muted)]">
                      {readResult.fileType || "image/jpeg"} {readResult.convertedToJpeg ? `(from ${readResult.originalType})` : ""}
                    </p>
                  </div>
                  <div className="rounded-full bg-white px-4 py-2 text-xs font-semibold uppercase tracking-[0.2em] text-[var(--accent-deep)]">
                    {readResult.convertedToJpeg ? "Converted" : "Loaded"}
                  </div>
                </div>
              ) : null}
            </div>

            <div className="glass-panel rounded-[1.75rem] p-5 sm:p-6">
              <p className="text-sm font-semibold uppercase tracking-[0.2em] text-[var(--accent-deep)]">
                2. Select Device
              </p>
              <select
                value={selectedPresetId}
                onChange={(event) => setSelectedPresetId(event.target.value)}
                className="mt-4 w-full rounded-2xl border border-[var(--line)] bg-white px-4 py-3 text-sm text-[var(--foreground)] outline-none"
              >
                {devicePresets.map((preset) => (
                  <option key={preset.id} value={preset.id}>
                    {preset.brand} {preset.name}
                  </option>
                ))}
              </select>

              <label className="mt-4 flex items-start gap-3 rounded-[1.25rem] border border-[var(--line)] bg-white/70 px-4 py-4">
                <input
                  type="checkbox"
                  checked={sanitizeEnabled}
                  onChange={(event) => setSanitizeEnabled(event.target.checked)}
                  className="mt-1 h-4 w-4 accent-[var(--accent)]"
                />
                <span className="text-sm leading-7 text-[var(--muted)]">
                  <span className="block font-semibold text-[var(--foreground)]">Sanitize mode</span>
                  Removes Photoshop, GIMP, previous device traces, and extra EXIF blocks to create a clean metadata profile.
                </span>
              </label>

              {selectedPreset ? (
                <div className="mt-4 rounded-[1.5rem] border border-[var(--line)] bg-white/70 p-4">
                  <p className="text-sm font-semibold text-[var(--foreground)]">{selectedPreset.name}</p>
                  <div className="mt-3 space-y-2 text-sm text-[var(--muted)]">
                    <p>Make: {selectedPreset.make}</p>
                    <p>Model: {selectedPreset.model}</p>
                    <p>Software: {selectedPreset.software}</p>
                    <p>Lens: {selectedPreset.lensModel}</p>
                  </div>
                </div>
              ) : null}

              <button
                type="button"
                onClick={handleInject}
                disabled={!readResult || busy}
                className="mt-5 w-full rounded-2xl bg-[var(--accent)] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[var(--accent-deep)] disabled:cursor-not-allowed disabled:opacity-55"
              >
                Sanitize + Inject Metadata
              </button>

              {downloadUrl ? (
                <a
                  href={downloadUrl}
                  download={updatedMetadata?.OutputFileName ? String(updatedMetadata.OutputFileName) : buildDeviceFileName(selectedPreset)}
                  onClick={() => setShowDownloadPopup(true)}
                  className="mt-3 inline-flex w-full items-center justify-center gap-3 rounded-2xl border border-[#2b7a43] bg-gradient-to-b from-[#46bf69] to-[#2f9e53] px-5 py-3 text-center text-sm font-semibold text-white shadow-[0_14px_30px_rgba(47,158,83,0.28)] transition hover:from-[#3eb362] hover:to-[#288948] active:translate-y-[1px]"
                >
                  <span className="inline-flex h-7 w-7 items-center justify-center rounded-full bg-white/18" aria-hidden="true">
                    <svg viewBox="0 0 20 20" className="h-4 w-4 fill-none stroke-current stroke-[1.8]">
                      <path d="M10 3.5v8.5" strokeLinecap="round" />
                      <path d="M6.75 9.75 10 13l3.25-3.25" strokeLinecap="round" strokeLinejoin="round" />
                      <path d="M4 15.5h12" strokeLinecap="round" />
                    </svg>
                  </span>
                  Modified Image Download
                </a>
              ) : null}
            </div>
          </div>
        </div>
      </section>

      <section className="mt-8 grid gap-6 lg:grid-cols-2">
        <div className="glass-panel rounded-[1.75rem] p-5 sm:p-6">
          <div className="flex flex-col items-start gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.2em] text-[var(--accent-deep)]">
                3. Current Metadata
              </p>
              <p className="mt-2 text-sm text-[var(--muted)]">Grouped metadata inspector for the uploaded image</p>
            </div>
            {readResult?.previewUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={readResult.previewUrl}
                alt="Uploaded preview"
                className="h-16 w-16 self-start rounded-2xl object-cover sm:h-20 sm:w-20"
              />
            ) : null}
          </div>

          {readResult ? (
            <div className="mt-5 grid gap-3 sm:grid-cols-3">
              <div className="rounded-2xl border border-[var(--line)] bg-white/70 px-4 py-3">
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--muted)]">File Type</p>
                <p className="mt-1 text-sm text-[var(--foreground)]">{readResult.fileType}</p>
              </div>
              <div className="rounded-2xl border border-[var(--line)] bg-white/70 px-4 py-3">
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--muted)]">File Size</p>
                <p className="mt-1 text-sm text-[var(--foreground)]">{formatBytes(readResult.fileSize)}</p>
              </div>
              <div className="rounded-2xl border border-[var(--line)] bg-white/70 px-4 py-3">
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-[var(--muted)]">Converted</p>
                <p className="mt-1 text-sm text-[var(--foreground)]">{readResult.convertedToJpeg ? "Yes" : "No"}</p>
              </div>
            </div>
          ) : null}

          {readResult?.aiDetected ? (
            <div className="mt-5 rounded-[1.5rem] border border-[#f0a3a3] bg-[#ffe3e3] px-4 py-4 shadow-[inset_0_1px_0_rgba(255,255,255,0.3)]">
              <p className="inline-flex rounded-full bg-[#ffd0d0] px-3 py-1 text-sm font-semibold uppercase tracking-[0.18em] text-[#b42318]">
                AI Generated Detected
              </p>
              <p className="mt-2 text-sm leading-7 text-[#912018]">
                This uploaded image appears to contain AI-generation traces in its current metadata.
              </p>
            </div>
          ) : null}

          {readResult?.editorDetected ? (
            <div className="mt-5 rounded-[1.5rem] border border-[#d92d20] bg-[#ffd6d3] px-4 py-4 shadow-[inset_0_1px_0_rgba(255,255,255,0.28)]">
              <p className="inline-flex rounded-full bg-[#ffbdb7] px-3 py-1 text-sm font-semibold uppercase tracking-[0.18em] text-[#b42318]">
                Photoshop / Edited Image Detected
              </p>
              <p className="mt-2 text-sm leading-7 text-[#912018]">
                This uploaded image appears to contain Photoshop or editor traces in its current metadata.
              </p>
            </div>
          ) : null}

          {readResult ? (
            <>
              <div className="mt-5 flex flex-col gap-3 sm:flex-row">
                <input
                  type="text"
                  value={inspectorQuery}
                  onChange={(event) => setInspectorQuery(event.target.value)}
                  placeholder="Search fields, for example make / model / date / gps"
                  className="w-full rounded-2xl border border-[var(--line)] bg-white px-4 py-3 text-sm text-[var(--foreground)] outline-none"
                />
                <button
                  type="button"
                  onClick={() => setShowRawMetadata((current) => !current)}
                  className="rounded-2xl border border-[var(--line)] bg-white px-4 py-3 text-sm font-semibold text-[var(--foreground)]"
                >
                  {showRawMetadata ? "Grouped View" : "Raw JSON"}
                </button>
                <button
                  type="button"
                  onClick={() => setIsCurrentMetadataExpanded((current) => !current)}
                  className="inline-flex items-center justify-center gap-3 rounded-2xl border border-[#2b7a43] bg-gradient-to-b from-[#46bf69] to-[#2f9e53] px-5 py-3 text-sm font-semibold text-white shadow-[0_14px_30px_rgba(47,158,83,0.28)] transition hover:from-[#3eb362] hover:to-[#288948] active:translate-y-[1px]"
                >
                  <span className="inline-flex h-7 w-7 items-center justify-center rounded-full bg-white/18" aria-hidden="true">
                    <svg viewBox="0 0 20 20" className="h-4 w-4 fill-none stroke-current stroke-[1.8]">
                      <path d="M4 10h12" strokeLinecap="round" />
                      {isCurrentMetadataExpanded ? null : <path d="M10 4v12" strokeLinecap="round" />}
                    </svg>
                  </span>
                  {isCurrentMetadataExpanded ? "Hide Metadata" : "Show Metadata"}
                </button>
              </div>

              {isCurrentMetadataExpanded ? (
                <div className="mt-5 max-h-[34rem] overflow-y-auto pr-1">
                  {renderMetadataItems(readResult.metadata, "current")}
                </div>
              ) : null}
            </>
          ) : null}
        </div>

        <div className="glass-panel rounded-[1.75rem] p-5 sm:p-6">
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-[var(--accent-deep)]">
            4. Injected metadata
          </p>
          <p className="mt-2 text-sm text-[var(--muted)]">
            Metadata found after applying the preset will appear here
          </p>

          <div className="mt-5 max-h-[34rem] overflow-y-auto pr-1">
            {updatedMetadata ? renderMetadataItems(updatedMetadata, "injected") : (
              <div className="rounded-[1.5rem] border border-dashed border-[var(--line)] bg-white/55 px-5 py-8 text-sm leading-7 text-[var(--muted)]">
                Nothing has been injected yet. Upload a JPG image first, then select a Samsung preset
                and press the inject button.
              </div>
            )}
          </div>
        </div>
      </section>

      {showDownloadPopup ? (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-[rgba(34,24,16,0.42)] px-4">
          <div className="w-full max-w-md rounded-[1.75rem] border border-[var(--line)] bg-[#fffaf2] p-6 shadow-[0_30px_80px_rgba(70,44,24,0.18)]">
            <p className="text-xs font-semibold uppercase tracking-[0.24em] text-[var(--accent-deep)]">
              Congratulations
            </p>
            <h2 className="mt-3 text-2xl font-semibold text-[var(--foreground)]">
              Your modified image is downloading
            </h2>
            <p className="mt-3 text-sm leading-7 text-[var(--muted)]">
              Thanks for using <span className="font-semibold text-[var(--accent-deep)]">2nur.com</span>
            </p>
            <button
              type="button"
              onClick={() => setShowDownloadPopup(false)}
              className="mt-5 w-full rounded-2xl bg-[var(--accent)] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[var(--accent-deep)]"
            >
              Close
            </button>
          </div>
        </div>
      ) : null}
    </main>
  );
}
